language: python

dist: focal

matrix:
  include:
    - python: '3.7'
      env: TOKENV=py37-coverage
    - python: '3.7'
      env: TOXENV=pylama

install:
  - pip install tox coveralls

script:
  - tox

sudo: required

after_success:
  - coveralls
